config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  # resources :lists
  resources :corps do
    resources :resumes do
      resources :cards
    end
  end

  resources :ques
  resources :events 
    
  # get '/lists/:resume_id', to: 'lists#index'
  get '/lists', to: 'lists#index'
  get '/lists/list', to: 'lists#list'
  get '/lists/formque', to: 'lists#formque'
  get '/lists/formcorp', to: 'lists#formcorp'
  get '/lists/resumecards', to: 'lists#resumecards'
  get '/lists/quecards', to: 'lists#quecards'
  get '/lists/corpcards', to: 'lists#corpcards'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :resume
end

app/models/corp.rb
class Corp < ApplicationRecord
    has_many :resume,dependent: :destroy
    def cards
        resumes = Resume.where(corp_id: id)
        resumes_id= []
        resumes.each do |resume|
            resumes_id.push(resume.id)
        end
        Card.where(resume_id: resumes_id)

        # resumes = Resume.where(corp_id: corp_id)
        # corp_cards= []
        # resumes.each do |resume|
        #     @cards = Card.where(resume_id: resume.id)
        #     corp_cards.push(@cards)
        # end
        # binding.pry
        # corp_cards
    end
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/que.rb
class Que < ApplicationRecord
end

app/models/resume.rb
class Resume < ApplicationRecord
    has_many :card,dependent: :destroy
    belongs_to :corp
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    def index
        @cards = Card.where(resume_id: params[:resume_id])
        @resume = Resume.find_by(id: params[:resume_id])
        @corp = Corp.find_by(id: params[:corp_id])
    end
    def new
        @card = Card.new
        @resume = Resume.find_by(id: params[:resume_id])
        @que = Que.all
    end
      
    def create
        @card = Card.create(card_params)
        redirect_to corp_resume_cards_path
    end

    def edit
        @card = Card.find(params[:id])
        @que = Que.new
    end
    
    def update
        @card = Card.find(params[:id])
        @card.update(card_params)
        redirect_to corp_resume_cards_path
    end


    private
    def card_params
      params.require(:card).permit(:que,:content,:resume_id,:que_type)
    end
end

app/controllers/corps_controller.rb
class CorpsController < ApplicationController
    def index
        @corps = Corp.all
    end

    def new
        @corp = Corp.new
    end
    
    def create
        @corp = Corp.create(corp_params)
        redirect_to corps_path
    end
    
    private
    def corp_params
          params.require(:corp).permit(:name)
    end
    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def index
        @events = Event.all
    end

    def new
        @event = Event.new
        @corps = Corp.all
    end
    
    def create
        @event = Event.create(event_params)
        redirect_to lists_path
    end

    private
    def event_params
          params.require(:event).permit(:title,:content,:start_time,:corp_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   include ListsHelper
    def index
        id = vali_id(params[:resume_id])
        q_id = vali_id(params[:que_type])
        if id == -1 && q_id ==-1
          @cards = Card.all
        elsif id != -1 && q_id == -1
          @cards = Card.where(resume_id: id)
        elsif id == -1 && q_id != -1
          @cards = Card.where(que_type: q_id)
        end
        @resumes = Resume.all
        @corps = Corp.all
        @events = Event.all
    end

    def list
      @resumes = Resume.where(corp_id: params[:corp_id])
      render json: {
        html: render_to_string(partial: 'list', locals: { resumes: @resumes}) 
      }
    end

    def formque
      @ques = Que.all
      render json: {
        html: render_to_string(partial: 'formque', locals: { ques: @ques}) 
      }
    end

    def formcorp
      @corps = Corp.all
      render json: {
        html: render_to_string(partial: 'formcorp', locals: { corps: @corps}) 
      }
    end

    def resumecards
      per=4
      r_id = vali_id(params[:resume_id])
      @cards = Card.where(resume_id: r_id).page(params[:page]).per(per).order(:id)
      total = (Card.where(resume_id: r_id).count/per.to_f).ceil
      # binding.pry
      render json: {
        html: render_to_string(partial: 'card', locals: { cards: @cards,page: params[:page],total: total}) 
      }
    end

    def quecards
      per=4
      q_id = vali_id(params[:que_id])
      @cards = Card.where(que_type: q_id).page(params[:page]).per(per).order(:id)
      total = (Card.where(que_type: q_id).count/per.to_f).ceil
      render json: {
        html: render_to_string(partial: 'card', locals: {cards: @cards,page: params[:page],total: total}) 
      }
    end

    def corpcards
      corp_id = vali_id(params[:corp_id])

      @corp = Corp.find_by(id: corp_id)
      render json: {
        html: render_to_string(partial: 'card', locals: { cards: @corp.cards}) 
      }
    end
    
    private
    def card_params
      params.require(:card).permit(:que,:content,:resume_id)
    end
end

app/controllers/ques_controller.rb
class QuesController < ApplicationController
    def index
        @ques = Que.all
    end
    
    def new
        @que = Que.new
    end
    
    def create
        @que = Que.create(que_params)
        redirect_to corps_path
    end

    private
    def que_params
          params.require(:que).permit(:title)
    end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
    def index
        @resumes = Resume.all
    end
    def new
        @resume = Resume.new
        @corp = Corp.find_by(id: params[:corp_id])
    end
      
    def create
        @resume = Resume.new(resume_params)
        if @resume.save
            redirect_to corps_path
        else
            render action: :new
        end
    end

    private
    def resume_params
      params.require(:resume).permit(:title,:corp_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper

end

app/helpers/corps_helper.rb
module CorpsHelper
    def selectCorp(corps)
        corpSection={}
        corps.each do |corp|
            corpSection.store(corp.name,corp.id)
        end
        corpSection
    end
    def findCorp(cid)
        if cid != nil
            @corp = Corp.find_by(id: cid)
            @corp.name

        else
            ''
        end
    end
end

app/helpers/events_helper.rb
module EventsHelper

end

app/helpers/lists_helper.rb
module ListsHelper
    def selectEs(resumes)
        es={}
        resumes.each do |resume|
            es.store(resume.title,resume.id)
        end
        es
    end
    def vali_id(id)
        id=~/^[0-9]+$/ ? id : -1
    end

end

app/helpers/ques_helper.rb
module QuesHelper
    def selectQue(ques)
        queSection={}
        ques.each do |que|
            queSection.store(que.title,que.id)
        end
        queSection
    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/cards/edit.html.erb
<h1>Card編集</h1>
<%= form_with model: @card, url: { action: :update } do |f| %>
  <div><%= f.label :que %></div>
  <div><%= f.text_field :que %></div>
  <div><%= f.select 'resume_id',selectQue(@que), include_blank: true %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '質問内容の追加', new_que_path %>
<%= link_to '戻る', corps_path %>

app/views/cards/index.html.erb
<h1>ES</h1>
<table>
  <thead>
    <tr>
      <th>質問カード一覧</th>
    </tr>
  </thead>
  <tbody>
    <% @resume.card.each do |card| %>
      <tr>
        <td><%= card.que %></td>
        <td><%= card.content %></td>
        <td><%= link_to '編集', edit_corp_resume_card_path(id: card.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '質問カードの追加', new_corp_resume_card_path %>
<%= link_to 'ホームに戻る', corps_path %>

app/views/cards/new.html.erb
<h1>質問カードの追加</h1>
<%= form_with model: @card, url: { action: :create } do |f| %>
  <%= f.hidden_field :resume_id, value: @resume.id %>
  <div>質問内容</div>
  <div><%= f.text_field :que %></div>
  <div>回答</div>
  <div><%= f.text_field :content %></div>
  <div>質問タイプ</div>
  <div><%= f.select 'que_type',selectQue(@que), include_blank: true %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '質問内容の追加', new_que_path %>
<%= link_to '戻る', corp_resume_cards_path %>

app/views/corps/index.html.erb
<h1>ES作成企業一覧</h1>
<table>
  <thead>
    <tr>
      <th>企業名</th>
    </tr>
  </thead>
  <tbody>
    <% @corps.each do |corp| %>
      <tr>
        <td><%= corp.name %></td>
        <% corp.resume.each do |resume|%>
            <td><%= link_to resume.title , corp_resume_cards_path(corp,resume) %></td>
        <% end %>
        <td><%= link_to 'ESを追加', new_corp_resume_path(corp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '企業追加', new_corp_path %>
<%= link_to '質問内容の追加', new_que_path %>
<%= link_to '閲覧画面に戻る', lists_path %>

app/views/corps/new.html.erb
<h1>企業追加</h1>
<%= form_for(@corp) do |f| %>
  <div><%= f.label :name %></div>
  <div><%= f.text_field :name %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', corps_path %>

app/views/events/new.html.erb
<%= form_with model: @event, url: { action: :create } do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="time">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="corp">
    <%= form.select 'corp_id',selectCorp(@corps), include_blank: true %>
  </div>

  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EsSheetCom</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script
  src="https://code.jquery.com/jquery-3.6.0.min.js"
  integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
  crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_card.html.erb
    <div class = 'flexBox'>
    <% cards.each do |card| %>
    <div class="flexCard">
      <div class="queItem">
        <div>質問内容</div>
        <div><%= card.que %></div>
      </div>
      <div class="ansItem">
        <div>回答内容</div>
        <div><%= card.content %></div>
      </div>
    </div>
    <% end %>
    <br>
    </div>

    <div class = "pageButton">
      <button id="back">戻る</button>
      <%=page.to_s+"/"+total.to_s %>
      <button id="front">進む</button>
    </div>

app/views/lists/_formcorp.html.erb
<%= form_with url: "/lists", method: :get do |form| %>
  <%= form.label :qery, "企業名:" %>
  <%= form.select 'corp_id',options_from_collection_for_select(@corps, "id", "name") , {id: 'corp_select'},include_blank: true%>
  <%= form.select 'resume_id',[["ESを選択してください。",1]], include_blank: true %>
  <%= form.submit  "検索" %>
<% end %>

app/views/lists/_formque.html.erb
<div id = "form_type">
<%= form_with url: "/lists", method: :get do |form| %>
  <%= form.select 'que_type',selectQue(ques), include_blank: true %>
  <%= form.submit  "検索" %>
<% end %>
</div>

app/views/lists/_list.html.erb
<%= select '','resume_id',selectEs(resumes), include_blank: true %>

app/views/lists/index.html.erb
<script>
// <%# import jquery from "jquery-rails" %>
$(function(){
  var page=1;
  $(document).on('click', '#corp_id', function(){
		var corp_id = $('#corp_id option:selected').val();
		$.ajax({
			type:'GET',
			url:'/lists/list',
      data: {  // 送信するデータをハッシュ形式で指定
        corp_id: corp_id
      },
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('#resume_id').html(data_json.html);
      console.log(data_json);
    }).fail(function (data) {
      // error
      console.log('error');
    });
	})

  $("#que_button").on("click", function() {
		$.ajax({
			type:'GET',
			url:'/lists/formque',
      data:''
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('#form_type').html(data_json.html);
      // console.log(data_json);
      $("#corp_button").prop('disabled', false);
      $("#que_button").prop('disabled', true);
    }).fail(function (data) {
      // error
      console.log('error');
    });
  })
  $("#corp_button").on("click", function() {
    $.ajax({
			type:'GET',
			url:'/lists/formcorp',
      data:''
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('#form_type').html(data_json.html);
      $("#corp_button").prop('disabled', true);
      $("#que_button").prop('disabled', false);
    }).fail(function (data) {
      // error
      console.log('error');
    });
  })

  $(document).on('change', '#resume_id', function(){
		var resume_id = $('#resume_id option:selected').val();
    page = 1;
    resumecards(resume_id,page);
	})

  $(document).on('click', '#que_type', function(){
		var que_id = $('#que_type option:selected').val();
    page = 1;
    quecards(que_id,page);
	})

  $(document).on('click', '#back', function(){
    if(page<=1){
      page=1;
    }else{
      page--;
    }
    if($('#resume_id option:selected').val()!=null){
      var resume_id = $('#resume_id option:selected').val();
      resumecards(resume_id,page);
    }else if($('#que_type option:selected').val()!=null){
      var que_id = $('option:selected').val();
      quecards(que_id,page);
    }
	})
  
  $(document).on('click', '#front', function(){
    page++;
    if($('#resume_id option:selected').val()!=null){
      var resume_id = $('#resume_id option:selected').val();
      resumecards(resume_id,page);
    }else if($('#que_type option:selected').val()!=null){
      var que_id = $('#que_type option:selected').val();
      quecards(que_id,page);
    }
	})

  $(document).on('click', '#event', function(){
		var corp_id = $(this).val();
		$.ajax({
			type:'GET',
			url:'/lists/corpcards',
      data: {  // 送信するデータをハッシュ形式で指定
        corp_id: corp_id
      },
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('.contents').html(data_json.html);
    }).fail(function (data) {
      // error
      console.log('error');
    });
	})

  function resumecards(resume_id,page){
  $.ajax({
			type:'GET',
			url:'/lists/resumecards',
      data: {  // 送信するデータをハッシュ形式で指定
        resume_id: resume_id,
        page: page
      },
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('.contents').html(data_json.html);
      // console.log(data_json);
    }).fail(function (data) {
      // error
      console.log('error');
    });
  }

  function quecards(que_id,page){
    $.ajax({
			type:'GET',
			url:'/lists/quecards',
      data: {  // 送信するデータをハッシュ形式で指定
        que_id: que_id,
        page: page
      },
		}).done(function (data) {
      // success
      //取得jsonデータ
      var data_stringify = JSON.stringify(data);
      var data_json = JSON.parse(data_stringify);
      $('.contents').html(data_json.html);
    }).fail(function (data) {
      // error
      console.log('error');
    });
  }
});

</script>

<h1>ESカード一覧</h1>

<button id="que_button" type="button">質問モード</button>
<button id="corp_button" type="button" disabled>企業モード</button>
<div class = "tab_menu">
<div id = "form_type">
<%= form_with url: "/lists", method: :get do |form| %>
  <%= form.label :qery, "企業名:" %>
  <%= form.select :corp_id,options_from_collection_for_select(@corps, "id", "name") , {id: 'corp_select'},include_blank: true%>
  <%= form.select :resume_id,[["ESを選択してください。",1]], include_blank: true %>
  <%= form.submit  "検索" %>
<% end %>
</div>
</div>
<div class ="contents">
  <div class="flexBox">
    <% @cards.each do |card| %>
    <div class="flexCard">
      <div class="queItem">
        <div>質問内容</div>
        <div><%= card.que %></div>
      </div>
      <div class="ansItem">
        <div>回答内容</div>
        <div><%= card.content %></div>
      </div>
    </div>
    <% end %>
  </div>
</div>
<%= link_to 'ESカード作成画面', corps_path %>

<%= link_to '予定追加', new_event_path %>
<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>

  <% events.each do |event| %>
    <div>
      <button id="event" value=<%= event.corp_id %>><%= findCorp(event.corp_id) %></button> 
      <div><%= event.title %></div>
    </div>
  <% end %>
<% end %>

app/views/ques/new.html.erb
<h1>質問内容の追加</h1>
<%= form_with model: @que, url: { action: :create } do |f| %>
  <div><%= f.text_field :title %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', corps_path %>

app/views/resumes/new.html.erb
<h1>ESの追加</h1>
<%= form_with model: @resume, url: { action: :create } do |f| %>
  <%= f.hidden_field :corp_id, value: @corp.id %>
  <div><%= f.label :title %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', corps_path %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>